server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transfer_app?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: kodh1234
  jackson:
    serialization: 
      write-dates-as-timestamps: false #json 직렬화 날짜/시간을 문자열로 내보내줌